services:
  zenemy:
    build:
      context: .
      dockerfile: Dockerfile-zenemy
    command: /root/z-enemy -a kawpow -o stratum+tcp://kawpow.usa-west.nicehash.com:3385 -u 35wXssceVET45koSKXA93g6YKdfiMEzyDY
    # restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              # device_ids: ['0', '3']
              capabilities: [gpu]
